### ISSUE TITLE
Patch Tuesday Release - 2B

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1674]
# Patch Tuesday Release - 2B

## Tasks
1. - [x] Wait for the following Windows images to have been updated as part of the Windows Patch Tuesday release process:

      - [x] `mcr.microsoft.com/windows/nanoserver:1809`
      - [x] `mcr.microsoft.com/windows/nanoserver:1809-arm32v7`
      - [x] `mcr.microsoft.com/windows/nanoserver:1903`
      - [x] `mcr.microsoft.com/windows/nanoserver:1909`
1. - [x] Queue build of [dotnet-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=373) (internal MSFT link) with the following parameters:

          imageBuilder.pathArgs: --path '*nanoserver*'
1. - [x] Queue build of [dotnet-docker-nightly pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=359) (internal MSFT link) with the following parameters:

          imageBuilder.pathArgs: --path '*nanoserver*'
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-core](https://hub.docker.com/_/microsoft-dotnet-core)
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-core-nightly](https://hub.docker.com/_/microsoft-dotnet-core-nightly)
1. - [x] Confirm build for [dotnet-docker-samples](https://dev.azure.com/dnceng/internal/_build?definitionId=376) (internal MSFT link) was queued. This will be queued automatically by [dotnet-docker-tools-check-base-image-updates](https://dev.azure.com/dnceng/internal/_build?definitionId=536) when it detects that the product images have been updated (detection runs on a schedule). Alternatively, you can manually queue the samples build.
1. - [x] Confirm sample images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-core-samples](https://hub.docker.com/_/microsoft-dotnet-core-samples/)
1. - [x] Reply to .NET Release team with a status update email

**Comment by mthalman** [comment]
Image publishing is currently blocked due to connectivity issues on the Docker host machines.

**Comment by richlander** [comment]
**Update:** February image publishing remains blocked.

The root cause is that the February Windows container update requires container hosts to also have the February update. On Tuesday, our lab machines did not have the February update (they had the January update), so were not able to build February images as a result. While we did update our lab machines to the February update, we are waiting on the Windows team on guidance for what to do next. This change in Windows was apparently unintentional.

We will update this space before publishing Windows new Windows container images.

**Comment by mthalman** [comment]
There's a minor problem with the `Last Updated` column not being updated in Docker Hub page for the following two tags (these tags are up-to-date, it's just not displaying that they are):
* `mcr.microsoft.com/dotnet/core/aspnet:3.1.2-nanoserver-1809-arm32v7`
* `mcr.microsoft.com/dotnet/core-nightly/runtime:5.0.0-preview-nanoserver-1809-arm32v7`

**Comment by mthalman** [comment]
All images have been published.  Keeping this open until the minor tag issue in Docker Hub is resolved.

**Comment by mthalman** [comment]
Docker Hub content has been updated.  The release is now complete.
