### ISSUE TITLE
Transition plan for new repository names

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2337]
# Transition plan for new repository names

To help minimize the disruption of transitioning to the new Docker repository names for the .NET 5.0 release described in #1939, a new plan has been made to publish all supported images across all .NET versions (2.1, 3.1, 5.0) to these new repositories.  The original repository names will continue to be maintained for backwards compatibility.  References to the original repository names in our documentation will be updated to use the new repository names.

## Details

As part of the .NET 5.0 release, a new set of Docker repository names have been created that do not have "core" in the name. This aligns with the branding change from ".NET Core" to ".NET".  See the [announcement](https://github.com/dotnet/dotnet-docker/issues/1939) for details on these new repositories.

The original plan was to only publish 5.0+ Docker images to these new repositories and that 2.1/3.1 images would remain in the original repositories.  However, issues like #2334 exemplify scenarios where there is a burden in compensating for this lack of consistency in the repository names with .NET 5.0.  After further consideration we've determined that we should do more to reduce the friction associated with this repository name transition.  

By publishing 2.1 and 3.1 images to the new repository names, this friction can be reduced so that a single set of repository names can be used consistently across all infrastructure regardless of the .NET version.  In addition, the experience can be further improved by updating all our documentation to no longer refer to the original repository names with "core" in their name.  This effectively phases out usage of the original repository names.  However, they will still be maintained with up-to-date images in order to support those consumers that haven't yet been transitioned to the new repository names.  This is very similar to the [transition from Docker Hub to MCR](https://github.com/dotnet/announcements/issues/101).

## Transition Plan

1. - [x] Make the necessary changes in the nightly branch to publish all the 2.1 and 3.1 images to the new repository names and syndicate to the original repos: #2317.
1. - [x] Update MCR registration for dotnet/nightly repo to reference renamed readme files: https://github.com/microsoft/mcr/pull/1174
1. - [x] Remove obsolete MCR preview readmes for dotnet/nightly repo: https://github.com/microsoft/mcrdocs/pull/618
1. - [x] Update documentation in nightly branch to remove reference to original repository names: #2339
1. - [x] Contact MCR to have them initiate a request for Docker Hub to redirect the Docker Hub pages for the old nightly repos to the new repos:

    | Old Repo URL       | Redirect To     |
    | :------------- | :---------- |
    |  https://hub.docker.com/_/microsoft-dotnet-core-nightly-sdk/ | https://hub.docker.com/_/microsoft-dotnet-nightly-sdk/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-nightly-aspnet/ | https://hub.docker.com/_/microsoft-dotnet-nightly-aspnet/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-nightly-runtime/ | https://hub.docker.com/_/microsoft-dotnet-nightly-runtime/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-nightly-runtime-deps/ | https://hub.docker.com/_/microsoft-dotnet-nightly-runtime-deps/ | 
1. - [x] Once nightly branch is deemed stable, merge the changes into master branch.
1. - [x] MCR: Update registration for dotnet repos to reference renamed readme files: https://github.com/microsoft/mcr/pull/1186
1. - [x] MCR: Add redirects for dotnet/core repo readmes: https://github.com/microsoft/mcrdocs/pull/625
1. - [x] MCR: Move .NET samples to the new repository: https://github.com/microsoft/mcr/pull/1189
1. - [x] MCR: Remove obsolete MCR preview readmes for dotnet repos: https://github.com/microsoft/mcrdocs/pull/626
1. - [x] Contact MCR to have them initiate a request for Docker Hub to redirect the Docker Hub pages for the old official repos to the new repos:

    | Old Repo URL       | Redirect To     |
    | :------------- | :---------- |
    |  https://hub.docker.com/_/microsoft-dotnet-core-sdk/ | https://hub.docker.com/_/microsoft-dotnet-sdk/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-aspnet/ | https://hub.docker.com/_/microsoft-dotnet-aspnet/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-runtime/ | https://hub.docker.com/_/microsoft-dotnet-runtime/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-runtime-deps/ | https://hub.docker.com/_/microsoft-dotnet-runtime-deps/ | 
    |  https://hub.docker.com/_/microsoft-dotnet-core-samples/ | https://hub.docker.com/_/microsoft-dotnet-samples/ | 
1. - [x] Publish images to new repos

There is also supplemental work that should be done by other teams to support this transition:

- [x] Update Docker VS Code extension to use new repository names in scaffolded Dockerfiles: https://github.com/microsoft/vscode-docker/issues/2429
- [x] Update Docker Tools for VS to use new repository names  in scaffolded Dockerfiles: https://devdiv.visualstudio.com/DevDiv/_backlogs/backlog/Container%20Tools/Stories/?workitem=1237107
- [x] Update docs to reference new repository names: https://github.com/dotnet/docs/issues/21222
