### ISSUE TITLE
Consider merging the dotnet/dotnet-docker-samples GitHub repo into the dotnet/dotnet-docker GitHub repo

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#396]
@MichaelSimons commented on [Wed Jan 17 2018](https://github.com/dotnet/dotnet-docker-samples/issues/99)

The primary motivation behind this change is visibility.  The belief is that having all assets related to the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) Docker repo within one GitHub repo will help increase the visibility of everything.  If a user navigates to from [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) to the [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker) GitHub repo to view the Dockerfiles, there is a higher chance they will see the samples if there are within the same repo.  Having the samples in the same GitHub repo as the Dockerfiles will also help increase the visibility of incoming issues and PRs related to the samples.

The samples do cover usage scenarios beyond microsoft/dotnet.  For example the samples cover [aspnetcore](https://github.com/dotnet/dotnet-docker-samples/tree/master/aspnetapp).  This could be viewed as a positive as ASP.NET core is based on dotnetcore.  Seeing the ASP.NET core samples could help bring visibility to the fact that the ASP.NET core images exist and are based on the .NET core images.

**Work Items**

- [x] Check-in refactored samples into dotnet-docker
- [x] Update Docker Hub with new samples
- [x] Check in build infra into dotnet-docker
- [x] Move active issues from dotnet-docker-samples to dotnet-docker
- [x] Update dotnet-docker-samples readme and repo description to indicate new location
- [x] Mark dotnet-docker samples as archived
- [ ] Update GH repo link on Docker hub

**Comment by MichaelSimons** [comment]
The last piece remaining on this is to update the repo link on the [Docker Hub page](https://hub.docker.com/r/microsoft/dotnet-samples/).  Waiting on Docker for this.

**Comment by MichaelSimons** [comment]
Closing as primary work is done.  The broken link in Docker Hub is bring tracked with https://github.com/dotnet/dotnet-docker/issues/676.
